title: Ayano Yokoyama
shortname: AY
description: I design and localize digital content, combining UX writing and design with AI-assisted workflows.
url: https://ayanoyokoyama.github.io

author: Ayano Yokoyama
email: ayanoyokoyama@yahoo.com
linkedin: https://www.linkedin.com/in/ayanoyokoyama

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    output: true
