header_pages:
  - about.md

title: Ayano Yokoyama
shortname: AY
description: UX writing, content design, and AI-assisted workflows.
theme: minima
minima:
  skin: auto

author: Ayano Yokoyama
email: ayanoyokoyama@yahoo.com
linkedin: https://www.linkedin.com/in/ayanoyokoyama

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: https://ayanoyokoyama.github.io
defaults:
  - scope: { path: "" }
    values: { layout: page }

